### ISSUE TITLE
Probelauf

### ISSUE THREAD

**Issue by fretless1** [skasberger/github4newbies#11]
## Bemerkung
[Universität Wien](https://www.google.at/maps/place/University+of+Vienna/@48.2131855,16.3578617,17z/data=!3m1!4b1!4m5!3m4!1s0x476d07bdebd3d9dd:0xd7f665432f73f3c4!8m2!3d48.2131855!4d16.3600504)
Kommt darauf an wie wörtlich @skasberger die Instruktion nimmt (siehe Link).
Wahrscheinlich war eher die [Homepage der Uni Wien](https://www.univie.ac.at/#) gemeint.

## Wünsche
* Foliennummern
* Übersicht bzw. Ablaufplan am Beginn der Präsentation
* ideale Textmenge auf den Folien, weiter so!

**Comment by skasberger** [comment]
Danke für den Kommentar.

Wünsche sind notiert und werden nächstes Mal eingebaut.
