### ISSUE TITLE
Privatsphäre

### ISSUE THREAD

**Issue by Pirene** [skasberger/github4newbies#12]
## Bemerkung
[OREA](https://www.orea.oeaw.ac.at/) @skasberger 
## Wünsche
- Mehr Katzenbilder
- Gibt es private Möglichkeiten für Projekte, die nicht für alle einsehbar sein sollen?

**Comment by zmuvas** [comment]
Wer hat denn was zu verstecken =)?

**Comment by skasberger** [comment]
Danke für den Kommentar.

Katzenbilder werden eingebaut (mit abstand das meist gewünschte Feature) :)

Repos können entweder komplett privat oder komplett public sein.
