### ISSUE TITLE
Mehr infos zu git und git+LaTeX

### ISSUE THREAD

**Issue by JenniferHemmerich** [skasberger/github4newbies#14]
## Bemerkung: @skasberger 
Hier ist Jennifer von der [Pharmacoinformatik](https://pharminfo.univie.ac.at/)

## Wünsche
* Mehr infos über git selbst wären (im Rahmen eines anderen?) Workshops super
* Wie benutze ich git und LaTeX sinnvoll? (Oder wo finde ich infos dazu?)

#2 und  #4 fände ich auch wirklich super!

- [ ] Add Katzenbilder

- [ ] Translate

**Comment by skasberger** [comment]
Danke für deinen Kommentar.

wegen Latex und git: schau dir mal [Overleaf](https://www.overleaf.com/) und [ShareLatex](https://de.sharelatex.com/) an. 

Dem Bedarf nach Katzen werde ich zukünftig nachgehen. :)
