### ISSUE TITLE
Bekanntmachen in meinem Forschungsfeld

### ISSUE THREAD

**Issue by PR0209** [skasberger/github4newbies#15]
## MEIN INSTITUT ist an der Uni Wien lokalisiert
[Department für Ernährungswissenschaften](https://nutrition.univie.ac.at/)

@skasberger 

## MEINE WÜNSCHE

- wie kann ich mein Projekt in meiner Community bekannt machen?

- kann ich bestimmte Inhalte nur für bestimmte Personen sichtbar machen?

Danke für die Informationen

**Comment by skasberger** [comment]
Danke für deinen Kommentar. 

wegen Informations-Freigabe: ein Repo kann entweder komplett public oder komplett private sein.
Community bewerben: Bekannte in der Community fragen. Personen in der Community kennen lernen und darüber befragen, falls man noch niemanden kennt.

**Comment by PR0209** [comment]
Herzlichen Dank für die Infos und die Motivation Github zu nutzen.
ich habe bereits erste Ideen, in welchen Projekten ich es versuchen werde.
