### ISSUE TITLE
Erste Aufgabe im Workshop

### ISSUE THREAD

**Issue by bpiringer** [skasberger/github4newbies#16]
## BEMERKUNG
Ich freue mich darauf, dass heute von @skasberger im Workshop gelernte in meiner AG am ACDH-ÖAW (https://www.oeaw.ac.at/acdh/) anzuwenden!

## WÜNSCHE
* Mehr Zeit - 2 Stunden sind zu wenig!
* Eigener Workshop für Fortgeschrittene?
* Und vielleicht hilft's doch: Kaffeemaschine...

**Comment by skasberger** [comment]
Danke für deinen Kommentar.
