### ISSUE TITLE
Katzenbilder steigern Performance

### ISSUE THREAD

**Issue by zmuvas** [skasberger/github4newbies#4]
Lieber @skasberger,
Ich arbeite an der Uni Wien.

## Mein Wunsch
Was hältst du davon, Katzenbilder in den Workshop einzubauen?
Viele Infos zu Katzen gibt es hier: [KatzenWiki](https://de.wikipedia.org/wiki/Katzen)
## Süße Katzen
* Beispiel
### Dicke Katzen
* Beispiel
#### Mini Katzen

**Comment by zmuvas** [comment]
## Katzen 
*Miau* **Miau** ***Miau***

**Comment by fretless1** [comment]
Meinst du [so etwas?](https://myoctocat.com/build-your-octocat/)

**Comment by zmuvas** [comment]
***großartig!***

**Comment by skasberger** [comment]
Danke für die Kommentare.

Katzenbilder werden in Zukunft eingebaut. Und Octocats auch. :) :) :)
