### ISSUE TITLE
Nachfrage zu Folienlizenz

### ISSUE THREAD

**Issue by bernhard-r-schubert** [skasberger/github4newbies#5]
## Bemerkung

[Open Access Office](https://openaccess.univie.ac.at/) says hi @skasberger 

## Wünsche

* Repo unter CC BY, Folien unter CC BY-SA - was sind die Beweggründe?
* Eventuell mehr zu forking und branch-Verwaltung bringen?

**Comment by skasberger** [comment]
Danke für den Kommentar.

wegen Lizenz: weiß ich jetzt ehrlich gesagt gar nicht mehr genau, aber hab mir damals sehr viele Gedanken gemacht.
