### ISSUE TITLE
Mehr Vorträge

### ISSUE THREAD

**Issue by cybergretl** [skasberger/github4newbies#7]
## Wünsche der TU Wien und UNI Graz @skasberger 
* UNI Graz: Kaffee
* TU Wien: wir hätten auch gerne so einen Vortrag bei uns 
* Vernetzung zu Open Science Projekten 
* Vertiefende Workshops 
## Bemerkungen 
* TU Wien und UNI Graz
* alles super @skasberger

**Comment by skasberger** [comment]
Danke für den Kommentar. :)
